blink_symbol_level=0
chrome_pgo_phase=2
enable_iterator_debugging=false
enable_mse_mpeg2ts_stream_parser=true
enable_rust=true
enable_swiftshader=true
enable_updater=false
fatal_linker_warnings=false
ffmpeg_branding="Chrome"
is_clang=true
is_debug=false
is_official_build=true
proprietary_codecs=true
v8_symbol_level=0
symbol_level=0
concurrent_links=1
use_thin_lto=false
use_sysroot=false
use_system_xcode=true
mac_allow_system_xcode_for_official_builds_for_testing=true
use_clang_modules=false
use_unified_system_module=false
mac_sdk_min="14.0"
mac_deployment_target="13.0"
mac_min_system_version="13.0"

